import type { InsightExplanation, InsightFinding } from "@/types/intelligence";

export function generateInsightExplanation(
  finding: InsightFinding,
  relatedFindings: InsightFinding[] = [],
): InsightExplanation {
  const related = relatedFindings.filter(
    (item) =>
      item.productId === finding.productId && item.type !== finding.type,
  );

  switch (finding.type) {
  case "low_margin_product":
    return buildLowMarginExplanation(
      finding,
      related,
    );

  case "cost_increase":
    return buildCostIncreaseExplanation(
      finding,
      related,
    );

  case "return_anomaly":
    return buildReturnExplanation(
      finding,
      related,
    );

  case "supplier_opportunity":
    return buildSupplierOpportunityExplanation(
      finding,
    );

  case "supplier_issue":
    return buildSupplierIssueExplanation(
      finding,
    );

  default:
    return {
      whatHappened: finding.description,

      whyItMatters:
        "This finding may affect product profitability.",

      whatToInvestigate:
        "Review the related product and transaction data.",
    };
    }
}

function buildLowMarginExplanation(
  finding: InsightFinding,
  related: InsightFinding[],
): InsightExplanation {
  return {
    whatHappened: finding.description,

    whyItMatters:
      related.length > 0
        ? `Other signals were also detected for this product: ${related
            .map((item) => item.title)
            .join("; ")}.`
        : "The product is generating less contribution than its target margin.",

    whatToInvestigate:
      "Review purchase costs, direct costs, selling price, and recent returns.",
  };
}

function buildCostIncreaseExplanation(
  finding: InsightFinding,
  related: InsightFinding[],
): InsightExplanation {
  return {
    whatHappened: finding.description,

    whyItMatters:
      "Higher acquisition costs can reduce the contribution generated by each sale.",

    whatToInvestigate:
      related.length > 0
        ? `Also review: ${related.map((item) => item.title).join("; ")}.`
        : "Review recent supplier prices and compare them with earlier purchases.",
  };
}

function buildReturnExplanation(
  finding: InsightFinding,
  related: InsightFinding[],
): InsightExplanation {
  return {
    whatHappened: finding.description,

    whyItMatters:
      "Returns can reduce realized revenue while creating additional costs.",

    whatToInvestigate:
      related.length > 0
        ? `Also review: ${related.map((item) => item.title).join("; ")}.`
        : "Review return reasons and look for recurring product, delivery, or customer-expectation issues.",
  };
}

function buildSupplierOpportunityExplanation(
  finding: InsightFinding,
): InsightExplanation {
  return {
    whatHappened: finding.description,

    whyItMatters:
      "A lower historical acquisition cost could create an opportunity to improve product contribution.",

    whatToInvestigate:
      "Compare supplier quality, minimum order quantities, shipping costs, and payment terms before making a supplier change.",
  };
}

function buildSupplierIssueExplanation(
  finding: InsightFinding,
): InsightExplanation {
  return {
    whatHappened: finding.description,

    whyItMatters:
      "A sustained increase in supplier cost can put pressure on product margins.",

    whatToInvestigate:
      "Review recent supplier pricing and determine whether the increase is temporary or persistent.",
  };
}
